-- AlterTable
ALTER TABLE "FollowerList" ADD COLUMN     "follower" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "FollowingList" ADD COLUMN     "followingAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
